import os

ATERNITY_USER = os.environ['ATERNITY_USER']
ATERNITY_PW = os.environ['ATERNITY_PW']
SERVICENOW_USER = os.environ['SERVICENOW_USER']
SERVICENOW_PW = os.environ['SERVICENOW_PW']
SERVICE_NOW_EVENT_URL= os.environ['SERVICE_NOW_EVENT_URL']
ATERNITY_INCIDENT_URL =os.environ['ATERNITY_INCIDENT_URL']